### ISSUE TITLE
Funnel plugin shows drop numbers as the wrong percentage

### ISSUE THREAD

**Issue by emrys90** [mckn/mckn-funnel-panel#21]
What happened?
The actual drop is the inverse, so 13.37% is the drop. This is because the drop is from 187 to 162, which is a 13.37% decrease.
![funnel drop](https://github.com/mckn/mckn-funnel-panel/assets/20632855/39d00352-3e2f-4bad-b5e0-099a3d530cdf)

What did you expect to happen?
For the percentage drop display to match how many actually dropped, or for dropped text to be renamed to reflect what is actually being displayed, which is the percentage that advanced to the next step.

Did this work before?
Unknown, I'm new to Grafana

How do we reproduce it?
Create a funnel
Look at the drop numbers and percentage

Grafana platform?
A package manager (APT, YUM, BREW, etc.)

**Comment by mikebudzynski** [comment]
I am running into this issue as well. Sample data:
![image](https://github.com/user-attachments/assets/5482066c-bdae-4f86-8c93-374c0c777fab)

For example:
* A drop from 11 to 1 is described as 9.09% drop, while it should be 90.9% ((11-1)/11*100% = 90.9%).
* A change from 1 to 1 is described as 100% drop, while it should be 0% drop.
* A drop from 1 to 0 is described as 0% drop, while it should be 100% drop.

**Comment by mikebudzynski** [comment]
@mckn Based on my understanding of the code, the fix is as simple as changing this [line](https://github.com/mckn/mckn-funnel-panel/blob/main/src/components/BarGap.tsx#L20) from:
`const drop = toPercentage / fromPercentage;`
to:
`const drop = toPercentage - fromPercentage;`

**Comment by ryanhugh** [comment]
+1

Also, can someone share some sample data I can test with? thanks

**Comment by FinfinPlay** [comment]
Submitted a pull request with a possible fix: https://github.com/mckn/mckn-funnel-panel/pull/22

**Comment by mckn** [comment]
Fixed by https://github.com/mckn/mckn-funnel-panel/pull/22

**Comment by mckn** [comment]
Thanks for opening this issue! It is now fixed and will be out in the next release.

**Comment by realmorrisliu** [comment]
@mckn still facing this issue on version 1.1.2
![image](https://github.com/user-attachments/assets/dee72a36-fb39-40d3-8a14-271cae03d2ad)
![image](https://github.com/user-attachments/assets/8ca58bc9-f70d-4571-9bec-5af692345262)

**Comment by mckn** [comment]
@realmorrisliu hmm, so the last step has 95 items in it?

**Comment by realmorrisliu** [comment]
> @realmorrisliu hmm, so the last step has 95 items in it?

yes

**Comment by jangaraj** [comment]
I have a similar problem with 1.1.2 - I expect the first drop will be 20%, not 50%, etc.:
![obrázok](https://github.com/user-attachments/assets/fd57e694-9662-41f0-89d8-0c8ef6866481)
Simple data:
![obrázok](https://github.com/user-attachments/assets/9d530b1a-9e9d-4f66-9024-e69bc2bae039)

**Comment by mckn** [comment]
Thanks for reporting this. I will reopen this issue and have a look at it.

**Comment by mckn** [comment]
hmm, I can't reproduce this. Locally I get the following funnel with that data.

<img width="818" alt="Screenshot 2024-11-26 at 10 39 02" src="https://github.com/user-attachments/assets/9372b804-7d03-46dd-a68c-2bc809a49f6d">

**Comment by mckn** [comment]
I'm going to verify it in the shipped version as well.

**Comment by mckn** [comment]
So with the example:

From 100
To 80
Drop 20%

`(100-80)/100 = 0.2` and it will be displayed as `20%`

From 80
To 60
Drop 25%

`(80/60)/80 = 0.25` and it will be displayed as `25%`

**Comment by mckn** [comment]
Seems to work the same in the `1.1.2` version. Can you verify that you have done a refresh so there are no cache issues in the browser?

**Comment by mckn** [comment]
> Same issue in 1.1.2
> 
> right calculation should be Percentage  `Drop= (New Value−Old Value)/Old Value×100` i.e. (218−125)/125*100 = 74.4% so you need to change in line 20 `const drop = (fromPercentage - toPercentage) / fromPercentage;` to `const drop = (fromPercentage - toPercentage) / toPercentage;`

hmm, the example you provided is incorrect. 

The drop should be `42.6%` in your example. It went from 218 to 125. The drop is 93 units (218-125) and 93 is 42.6% of 218 units. So it dropped 42.6% from the previous step.

**Comment by enchantinggg4** [comment]
As a quick fix: add a new column with count 0, e.g. if your result was
`select 100 as top, 80 as middle, 30 as bottom;` it gives wrong percentages, but if you add 0 column
`select 100 as top, 80 as middle, 30 as bottom, 0 as fix;` percentages are ok, but at the cost of extra row in funnel

**Comment by ElaginDO** [comment]
> As a quick fix: add a new column with count 0, e.g. if your result was `select 100 as top, 80 as middle, 30 as bottom;` it gives wrong percentages, but if you add 0 column `select 100 as top, 80 as middle, 30 as bottom, 0 as fix;` percentages are ok, but at the cost of extra row in funnel

Yes. this working for us too.. 
Now the main question, how to hide zero value or add zero in the plugin code as defaultValue

**Comment by ElaginDO** [comment]
I`m editting code. so now it`s work perfectly
w8 new version on GitHub :))

**Comment by mfernandez-liftoff** [comment]
Hello, I believe I have also encountered the same issue described here. I have attached two screenshots along with a patch file which contains changes I made locally to address the issue.

I cloned the latest `main` branch (`67b4df5515c398614d21b77a256b1bc39a1c33a8`) and started the development environment. I configured a static data source with three entries (`10000`, `5000`, and `2500`).

The first screenshot shows the calculated drop off using the current code between `10000` and `5000` as 66.67% instead of the intuitive 50%. The second screenshot illustrates the difference in drop off calculation when my code changes are active.

I would be glad to create a PR with my changes should you wish to upstream them.



![default-code](https://github.com/user-attachments/assets/294a7fea-71ee-46de-9b9c-c12b2b681c9b)
![patched-code](https://github.com/user-attachments/assets/8647be40-4179-4052-ac59-f10d8a760b47)
[fix-drop-off.patch](https://github.com/user-attachments/files/18204040/fix-drop-off.patch)

**Comment by KGOH** [comment]
Hello. I believe I found a solution for this issue, I posted it in a duplicate issue here:
https://github.com/mckn/mckn-funnel-panel/issues/47#issuecomment-2561915080

**Comment by mckn** [comment]
hmm, this is interesting. Let me have a look at this and see if we can have this done  automagically under the hood.
